config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :pins do
    member do
      put "like", to: "pins#upvote"
    end
  end

  root "pins#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
  acts_as_votable
  belongs_to :user
  has_one_attached :image
  # I did not validate this image type need to look into it
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]

  def index
    @pins = Pin.all.order("created_at DESC")
  end

  def show

  end

  def new
    @pin = current_user.pins.build
  end

  def create
    @pin = current_user.pins.build(pin_params)

    if @pin.save
      redirect_to @pin, notice: "Successfully created new Pin"
    else
      render 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: "Successfully updated Pin!"
    else
      render 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to root_path, notice: "Successfully deleted pin!"
  end

  def upvote
    @pin.upvote_by current_user
    redirect_back fallback_location: root_path
   end

  private

  def pin_params
    params.require(:pin).permit(:title, :description, :image)
  end

  def find_pin
    @pin = Pin.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%=image_tag "clone.png", size: "40x40", class: "d-inline-block align-top", alt: "" %>
    <%= link_to "PinClone", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0"></ul>
      <ul class="navbar-nav mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <%= link_to "New Pin", new_pin_path, class: "nav-item nav-link" %>
          <%= link_to current_user.email, edit_user_registration_path, class: "nav-item nav-link" %>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-item nav-link" %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, class: "nav-item nav-link" %>
          <%= link_to "Login", new_user_session_path, class: "nav-item nav-link" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Romero Pin Board</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: "alert alert-info" %>
      <% end %>
      <main role="main">
        <%= content_for?(:content) ? yield(:content) : yield %>
      </main>
    </div>
  </body>
</html>

app/views/pins/_form.html.erb
<%= simple_form_for @pin, html: {multipart: true} do |f| %>

  <% if @pin.errors.any? %>
    <div id="errors">
      <%= pluralize(@pin.errors.count, "error") %>
      <h1>prevented this Pin from saving</h1>
      <ul>
        <% @pin.errors.full_messages.each do |msg| %>
          <li>
            <%= full_message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <% if @pin.image.attached? %>
      <%= image_tag @pin.image.variant(resize_to_limit: [400, 400]), class:"mx-auto d-block" %>
    <% end %>

    <%= f.label :image %>
    <%= f.file_field :image, {class: 'form-control'} %>
  </div>

  <div class="form-group">
    <%= f.input :title, input_html: {class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :description, input_html: {class: 'form-control'} %>
  </div>
  <p></p>
  <div class="btn-group pull-right">
    <%= f.button :submit, class: "btn" %>
    <%= link_to "Back", root_path, class: "btn btn-outline-dark" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="container container-small mt-4">
  <div class="card">
    <div class="card-header">
      <h1 class="card-title">Edit Pin</h1>
    </div>
    <div class="card-body">
      <%= render 'form' %>
      <p>
        <div class="btn btn-outline-dark"><%= link_to "Cancel", pin_path %></div>
      </p>
    </div>
  </div>
</div>

app/views/pins/index.html.erb
<script src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js" integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous" async></script>
<p>
  <%= image_tag("bgclone.jpg", class: "img-fluid d-block mx-auto", :alt => "background") %>
</p>

<div class="container mt-4">
  <div class="row" data-masonry='{"percentPosition": true }'>
    <% @pins.each do |pin| %>
      <div class="col-sm-6 col-lg-4 mb-4">
        <div class="card">
          <% if pin.image.attached? %>
            <div class="card-img-top bg-dark">
              <%= image_tag pin.image.variant(resize_to_limit: [400, 400]), class: "mx-auto d-block" %>
            </div>
          <% end %>
          <div class="card-body text-center">
            <h5 class="card-title"><%= link_to pin.title, pin %></h5>
            <p class="card-text"><%= pin.description %></p>
          </div>
          <div class="card-footer text-muted text-end">
            <small><svg xmlns="https://www.w3.org/2000/svg" width="16" height="16" fill="#dc3545" class="bi bi-bookmark-heart-fill" viewBox="0 0 16 16">
                <path d="M2 15.5a.5.5 0 0 0 .74.439L8 13.069l5.26 2.87A.5.5 0 0 0 14 15.5V2a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v13.5zM8 4.41c1.387-1.425 4.854 1.07 0 4.277C3.146 5.48 6.613 2.986 8 4.412z"/>
              </svg>
              <%= pin.get_upvotes.size %></small>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pins/new.html.erb
<div class="container container-small mt-4">

    <div class="card">
      <div class="card-header">
        <h1 class="card-title"> New Pin </h1>
      </div>
      <div class="card-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/pins/show.html.erb
<div class="container container-small mt-5 d-flex justify-content-center">
  <div class="card text-center">
    <% if @pin.image.attached? %>
      <div class="card-img-top bg-dark">
        <%= image_tag @pin.image.variant(resize_to_fill:[600,400]), class:"mx-auto d-block" %>
      </div>
    <% end %>
    <div class="card-body text-center">
      <h1 class="card-title"><%= @pin.title %></h1>
      <p class="card-text"><%= @pin.description %></p>
    </div>
    <div class="card-footer text-muted">
      <div class="row">
        <div class="col">
          <small class="text-muted">Submitted by <%= @pin.user.email %></small>
        </div>
        <div class="col text-end">
          <div class="btn-group pull-right">
            <%= link_to like_pin_path(@pin), method: :put, class: "btn btn-outline-dark" do %>
              <svg xmlns="https://www.w3.org/2000/svg" width="16" height="16" fill="#dc3545" class="bi bi-bookmark-heart-fill" viewBox="0 0 16 16">
                <path d="M2 15.5a.5.5 0 0 0 .74.439L8 13.069l5.26 2.87A.5.5 0 0 0 14 15.5V2a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v13.5zM8 4.41c1.387-1.425 4.854 1.07 0 4.277C3.146 5.48 6.613 2.986 8 4.412z"/>
              </svg>
              <%= @pin.get_upvotes.size %>
            </span>
          <% end %>
          <% if user_signed_in? %>
            <%= link_to "Edit", edit_pin_path, class: "btn btn-outline-dark" %>
            <%= link_to "Delete", pin_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-dark" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>